# Generated by Django 5.1.2 on 2025-02-20 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=20)),
                ('climate', models.CharField(max_length=20)),
                ('suitable_species', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('diet', models.CharField(choices=[('Carnivore', 'Carnivore'), ('Herbivore', 'Herbivore'), ('Omnivore', 'Omnivore')], max_length=20)),
                ('lifespan', models.IntegerField()),
                ('behaviour', models.CharField(max_length=50)),
                ('habitat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Digital_Zoo_Management.habitat')),
            ],
        ),
    ]
