# Generated by Django 5.1.2 on 2025-02-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0002_careroutine_zookeeper_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='suitable_species',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
