# Generated by Django 5.1.2 on 2025-02-25 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0003_alter_habitat_suitable_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='habitat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='Digital_Zoo_Management.habitat'),
        ),
    ]
