# Generated by Django 5.1.2 on 2025-03-04 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0005_careroutine_zookeeper_zookeeper_email_zookeeper_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careroutine',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
