# Generated by Django 5.1.2 on 2025-03-04 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0006_careroutine_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='activity_description',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='date_time',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='care_routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Digital_Zoo_Management.careroutine'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='careroutine',
            name='zookeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Digital_Zoo_Management.zookeeper'),
        ),
    ]
