# Generated by Django 5.1.2 on 2025-03-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0007_remove_activitylog_activity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='care_routine',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Digital_Zoo_Management.careroutine'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='zookeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Digital_Zoo_Management.zookeeper'),
        ),
    ]
