# Generated by Django 5.1.2 on 2025-03-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0009_alter_activitylog_care_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='care_routine_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='zookeeper_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
