# Generated by Django 5.1.2 on 2025-03-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0010_activitylog_care_routine_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='care_routine_name',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='zookeeper_name',
        ),
    ]
