# Generated by Django 5.1.2 on 2025-03-13 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0016_remove_membership_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
