# Generated by Django 5.1.2 on 2025-03-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0019_alter_membership_tier_alter_specialevent_min_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Basic'), (2, 'Premium'), (3, 'VIP')]),
        ),
        migrations.AlterField(
            model_name='specialevent',
            name='min_tier',
            field=models.CharField(choices=[(1, 'Basic'), (2, 'Premium'), (3, 'VIP')], max_length=20),
        ),
    ]
