# Generated by Django 5.1.2 on 2025-03-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0021_alter_specialevent_min_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='tier',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialevent',
            name='min_tier',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=20),
        ),
    ]
