# Generated by Django 5.1.2 on 2025-03-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0022_alter_membership_tier_alter_specialevent_min_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
