# Generated by Django 5.1.2 on 2025-03-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Zoo_Management', '0023_alter_eventregistration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='status',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
